eval_thetas:
- 0.7
experiment: A3_geometry
sweep:
- drop_desc:
  - dist
  name: no_dist
- drop_desc:
  - spread
  name: no_spread
- drop_desc:
  - count
  name: no_count
- drop_desc:
  - cx
  - cy
  - cz
  - dist
  - count
  name: only_spread
type: standard
